services:
    redis:
        build:
            context: ./requirements/redis
            dockerfile: Dockerfile 
        image: redis
        pull_policy: never
        container_name: redis
        tty: true
        ports:
            - "6379:6379"
        volumes:
            - redis_config:/etc/redis
        networks: 
            - inception_net 
        restart: on-failure

    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        pull_policy: never
        container_name: mariadb
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - mariadb_config:/etc/mysql
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    wordpress:
        depends_on:
            - mariadb
            - redis
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        pull_policy: never
        container_name: wordpress
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - wordpress_web:/var/www/wordpress
            - wordpress_php:/etc/php
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    nginx:
        depends_on:
            - adminer
            - wordpress
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        pull_policy: never
        container_name: nginx
        tty: true
        ports:
            - "443:443"
        volumes:
            - wordpress_web:/var/www/wordpress
            - adminer_web:/var/www/adminer
            - nginx_config:/etc/nginx
            - nginx_ssl:/etc/ssl/inception
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    vsftpd:
        depends_on:
            - wordpress
        build:
            context: ./requirements/vsftpd
            dockerfile: Dockerfile
        image: vsftpd
        pull_policy: never
        container_name: vsftpd
        tty: true
        ports:
            - "21:21"
            - "10000-10005:10000-10005"
        volumes:
            - wordpress_web:/var/www/wordpress
            - vsftpd_config:/etc/vsftpd
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    adminer:
        depends_on:
            - mariadb
            - wordpress
        build:
            context: ./requirements/adminer
            dockerfile: Dockerfile
        image: adminer
        pull_policy: never
        container_name: adminer
        tty: true
        ports:
            - "9001:9001"
        volumes:
            - adminer_web:/var/www/adminer
            - adminer_php:/etc/php
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure
    
    exim:
        depends_on:
            - wordpress
        build:
            context: ./requirements/exim
            dockerfile: Dockerfile
        image: exim
        pull_policy: never
        container_name: exim
        tty: true
        ports:
            - "25:25"
        volumes:
            - exim_config:/etc/exim4
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure
        
    apache:
        build:
            context: ./requirements/apache
            dockerfile: Dockerfile
        image: apache
        pull_policy: never
        container_name: apache
        tty: true
        ports:
            - "8443:8443"
        volumes:
            - apache_config:/etc/apache2
            - apache_web:/var/www
            - apache_ssl:/etc/ssl/inception
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

networks:
    inception_net:
        driver: bridge

volumes:
    wordpress_php:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/wordpress/php

    wordpress_web:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/wordpress/web-document 

    nginx_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/nginx/configuration

    nginx_ssl:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/nginx/ssl

    mariadb_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/mariadb/configuration

    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/mariadb/data

    redis_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/redis/configuration

    vsftpd_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/vsftpd/configuration

    adminer_web:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/adminer/web-document

    adminer_php:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/adminer/php
    
    exim_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/exim/configuration

    apache_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/apache/configuration

    apache_web:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/apache/web-document

    apache_ssl:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tayou/data/apache/ssl
