services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    pull_policy: never
    container_name: nginx
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/web-document:/var/www
      - ./requirements/nginx/configuration:/etc/nginx

    
   

