services:
    redis:
        build:
            context: ./requirements/bonus/redis
            dockerfile: Dockerfile 
        image: redis
        pull_policy: never
        container_name: redis
        tty: true
        networks: 
            - inception_net 
        restart: on-failure

    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        pull_policy: never
        container_name: mariadb
        tty: true
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    wordpress:
        depends_on:
            - mariadb
            - redis
            - exim
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        pull_policy: never
        container_name: wordpress
        tty: true
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    nginx:
        depends_on:
            - adminer
            - wordpress
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        pull_policy: never
        container_name: nginx
        tty: true
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress
            - adminer:/var/www/adminer
            - ssl:${SSL_PATH}
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    vsftpd:
        depends_on:
            - wordpress
        build:
            context: ./requirements/bonus/vsftpd
            dockerfile: Dockerfile
        image: vsftpd
        pull_policy: never
        container_name: vsftpd
        tty: true
        ports:
            - "21:21"
            - "10000-10005:10000-10005"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

    adminer:
        depends_on:
            - mariadb
            - wordpress
        build:
            context: ./requirements/bonus/adminer
            dockerfile: Dockerfile
        image: adminer
        pull_policy: never
        container_name: adminer
        tty: true
        volumes:
            - adminer:/var/www/adminer
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure
    
    exim:
        build:
            context: ./requirements/bonus/exim
            dockerfile: Dockerfile
        image: exim
        pull_policy: never
        container_name: exim
        tty: true
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure
        
    apache:
        build:
            context: ./requirements/bonus/apache
            dockerfile: Dockerfile
        image: apache
        pull_policy: never
        container_name: apache
        tty: true
        ports:
            - "8443:8443"
        volumes:
            - apache:/var/www
            - ssl:${SSL_PATH}
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: on-failure

networks:
    inception_net:
        driver: bridge

volumes:
    ssl:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/ssl

    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/wordpress

    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/mariadb

    adminer:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/adminer

    apache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/apache
