services:
    redis:
        build:
            context: ./requirements/redis
            dockerfile: Dockerfile
        image: redis
        pull_policy: never
        container_name: redis
        tty: true
        ports:
            - "6379:6379"
        volumes:
            - redis_config:/etc/redis
        networks:
            - inception_net
        restart: alwalys

    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        pull_policy: never
        container_name: mariadb
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - mariadb_config:/etc/mysql/mariadb.conf.d
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: alwalys

    wordpress:
        depends_on:
            - mariadb
            - redis
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        pull_policy: never
        container_name: wordpress
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - wordpress_php:/etc/php
            - wordpress_web:/var/www/html/wordpress
        networks:
            - inception_net
        env_file:
            - ./.env
        restart: alwalys

    nginx:
        depends_on:
            - wordpress
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        pull_policy: never
        container_name: nginx
        tty: true
        ports:
            - "443:443"
        volumes:
            - wordpress_web:/var/www/html
            - nginx_config:/etc/nginx
            - nginx_ssl:/etc/ssl
        networks:
            - inception_net
        restart: alwalys

networks:
    inception_net:
        driver: bridge

volumes:
    wordpress_php:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/wordpress/php

    wordpress_web:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/wordpress/web-document 

    nginx_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/nginx/configuration

    nginx_ssl:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/nginx/ssl

    mariadb_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/mariadb/configuration

    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/mariadb/data

    redis_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/tayou/Desktop/inception/srcs/requirements/redis/configuration

