route:
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 10m
  receiver: 'seonlim'

receivers:
- name: 'seonlim'
  email_configs:
  - to: ${ALERTMANAGER_EMAIL_TO}
    from: ${ALERTMANAGER_EMAIL_FROM}
    smarthost: smtp.gmail.com:587
    auth_username: ${ALERTMANAGER_AUTH_USERNAME}
    auth_password: ${ALERTMANAGER_AUTH_PASSWORD}
